server:
  port: 8088
#  error:
#    include-binding-errors: always
#    include-exception: true
#    include-message: always


spring:
  application:
    name: 'spring-todo'

  datasource:
    driver-class-name: org.postgresql.Driver
    hikari:
      username: postgres
      password: postgres
      minimum-idle: 5
      maximum-pool-size: 10
      idle-timeout: 600_000
      max-lifetime: 1_800_000
      connection-timeout: 30_000
    url: jdbc:postgresql://localhost:5432/springtodo

  flyway:
    enabled: true
    user: postgres
    password: postgres
    schemas: public
    url: jdbc:postgresql://localhost:5432/springtodo
    locations: "classpath:db/migration"
    baseline-on-migrate: true

  data:
    redis:
      host: localhost
      port: 6379
  cache:
    type: redis
    redis:
      time-to-live: 60000
      cache-null-values: true


management:
  endpoints:
    web:
      exposure:
        include: health,metrics,info
    endpoint:
      health:
        show-details: always
      metrics:
        enabled: true
      info:
        enabled: true

springdoc:
  info:
    title: Spring Tasks
    version: 0.0.1
    description: This API exposes endpoints for to do tasks.
  servers:
    - url: http://localhost:8088
      description: Local Server.
    - url: http://localhost:8088
      description: Dev Server.
    - url: http://localhost:8088
      description: Prod Server.
  api-docs:
    enabled: true
    path: /spring-todo-api-docs
  swagger-ui:
    enabled: true
    path: /spring-todo-ui
    try-it-out-enabled: true
    operations-sorter: method
    tags-sorter: alpha
    filter: true
  packages-to-scan:
    - "com.emobile.springtodo"